### ISSUE TITLE
Support zipped data pack

### ISSUE THREAD

**Issue by mdn522** [vberlier/mcpack#19]
Can you add support for loading and writing zipped data pack

**Comment by vberlier** [comment]
Sure, I'll be working on it shortly. In the meantime you can take a look at the builtin [`zipfile`](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.open) module.

**Comment by vberlier** [comment]
Quick update: I'm working on a package that will make it completely trivial for `mcpack` to support zipped and extracted data packs.

**Comment by vberlier** [comment]
I'm deprecating `mcpack` because I just released another project that supports both data packs and resource packs, zipped and unzipped formats, and much more https://github.com/vberlier/beet
