### ISSUE TITLE
Add tag property for Function.

### ISSUE THREAD

**Issue by tomgrin10** [vberlier/mcpack#22]
For easy tag placement without the whole `FunctionTag` thing.

**Comment by vberlier** [comment]
`mcpack` focuses on providing a hierarchy of python objects representing minecraft data packs. The goal is to keep the API as close as possible to the original file structure, maximizing the number of potential use-cases.

People familiar with data packs should be able to use the library just by extrapolating from the first few `README` examples. Introducing abstractions that combine several data pack features is something I try to avoid in this project, coupling `Function` and `FunctionTag` objects would make the API less predictable.

However, you're welcome to build your own abstraction layer on top of `mcpack`. For example, I'm (slowly) working on [`endermite`](https://github.com/vberlier/endermite), a high-level python framework for building data packs that uses `mcpack` under the hood.
