### ISSUE TITLE
Update for Minecraft 1.14

### ISSUE THREAD

**Issue by Eli112358** [vberlier/mcpack#31]
Are you working/planning on updating to mc-1.14?

For example, 1.14 adds a type to loot tables;
which currently causes:

`TypeError: __init__() got an unexpected keyword argument 'type'`

Could make it optional to be backwards compatible

**Comment by vberlier** [comment]
You're right I think I forgot about that. Just added the property ddcaba5d5975e3234e89a1f688cf79bcfd892c03. You can now specify the loot table type in the constructor. The default value is `'generic'`.

```py
LootTable(..., type='advancement_reward')
```

Do you think other things could cause issues with 1.14?

**Comment by vberlier** [comment]
By the way the fix is in version 0.3.6.

**Comment by vberlier** [comment]
Alright I'm going to close this issue but feel free to reopen it if you encounter another problem.
